// Real Google reviews, exported from the Sunlogic SA Google Business Profile
// (Google Takeout, location 13947336145699233678). Text is verbatim from each
// reviewer — do not edit wording. `url` is a Google Search results query
// ("Sunlogic SA reviews"), not a per-review deep link — Google doesn't expose
// a public URL format for a single review. A g.page/r/... short link would
// jump straight to Google Maps; the search query keeps the click inside
// Google Search, where the review snippet and rating show inline.
window.PLUGIN_REVIEWS = [
  {
    name: "Neil Harrower",
    avatar: null,
    rating: 5,
    text: "Great knowledge, great service.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "April 2026",
  },
  {
    name: "Jon Minster",
    avatar: null,
    rating: 5,
    text: "Great service from Stephan and his team. Each house and each install is different, and there will inevitably be some hiccups along the way, but Stephan was always available to problem-solve and make sure everything was working perfectly.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "March 2026",
  },
  {
    name: "James Alt",
    avatar: null,
    rating: 5,
    text: "We are very happy with our new solar system.  The team at Sunlogic advised us on our options, installed all the equipment expertly and explained how the hardware and software work.  We have seen a big drop off in our electricity costs and the system has worked very well.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "March 2026",
  },
  {
    name: "Johan Cronje",
    avatar: null,
    rating: 5,
    text: "Absolute pleasure working with Craig and the team. Always helpful and really went the extra mile with our house. I would Highly recommend them.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "December 2025",
  },
  {
    name: "Christof Sander",
    avatar: null,
    rating: 5,
    text: "Stephan and his team have done a fantastic job: Excellent consulting, fast communication and the construction team installed and commissioned everything perfectly within 2 days. The team worked very professionally and cleanly and I can only give an unreserved 5 stars as a rating! Highly recommended.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "March 2025",
  },
  {
    name: "Leentjie Strydom",
    avatar: null,
    rating: 5,
    text: "Thank you to Stephan and his team for the speedy and very professional installation.  The team worked tirelessly to complete the Solar installation within the committed timeframe.  Stephan went out of his way to guide us through the setup and customize to our needs.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "August 2023",
  },
  {
    name: "Dave Barron",
    avatar: null,
    rating: 5,
    text: "Great service from Stephan and the Sunlogic team. They were highly responsive, extremally informative and patient as I pestered them with tons of questions. We had an install that had to go outside and Stephan arranged to have a cabinet installed with the inverter to protect against elements.\nWould highly recommend them for the installation",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "July 2023",
  },
  {
    name: "Stephen Naude",
    avatar: null,
    rating: 5,
    text: "Clear and transparent quote with good understanding of my requirements. Installation team went above and beyond to finish, working late into the night. The outcome a super clean, professional and tidy installation. So far the system has worked flawlessly.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "May 2023",
  },
  {
    name: "Shenton Wood",
    avatar: null,
    rating: 5,
    text: "Great team with fantastic service before and after purchase.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "May 2023",
  },
  {
    name: "Kitesh Moodley",
    avatar: null,
    rating: 5,
    text: "Was looking at various solar options but until Sunlogic was recommended to me by friends I hadn't found the perfect fit. Right from the get go both Stephan and Craig have been fully involved discussing options and tailoring a package to suit our needs.\nInstallation was seamless and we've no issues since coming online.\nAfterhours services has been terrific with availability and responsiveness.\nHighly recommend this team to all friends and family 🙏",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "May 2023",
  },
  {
    name: "Demented Drew",
    avatar: null,
    rating: 5,
    text: "I was introduced to Craig and Stephan by my Sales Manager, who had used Sun Logic for several installations for our customers. After making a few calls and receiving nothing but positive feedback, I decided to call Craig for a quote for my home. Craig was at my house a few days later and spec’d a system suitable for our requirements. The installation was no small task, but each project stage was handled efficiently and professionally. Stephan and his Team kept me up to date at all times. I was never left wondering where we were on the project. I could not be happier with the result, neat installation and working better than expected. If you are going to make this investment, I highly recommend Sun Logic to get you the best equipment, professionally installed. My system comprises a Deye 8kva Inverter, 9kva Battery, and 12 Solar Panels.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "April 2023",
  },
  {
    name: "Laurelle Sham",
    avatar: null,
    rating: 5,
    text: "I have had a such a wonderful experience with the Sunlogic team. Craig and Stephan have gone out of their way to help me with installing an inverter and helping me with a subject I have little knowledge about. Their service has been beyond my expectation and I am very grateful to them for all their help.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "April 2023",
  },
  {
    name: "John Henshilwood",
    avatar: null,
    rating: 5,
    text: "Craig and Steph from Sun Logic have been fantastic! From quoting, to booking my install, arranging CoC the whole team did a great job. I would highly recommend them!",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "April 2023",
  },
  {
    name: "Dave Lehr",
    avatar: null,
    rating: 5,
    text: "Very happy with the power solution professionally installed by SunLogic in our office building. Great service and highly recommended.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "April 2023",
  },
  {
    name: "Brendon Shaw",
    avatar: null,
    rating: 5,
    text: "Dealing with Stephan, McDonald and team was an absolute pleasure.\n\nPerfect mix of honest feedback, explanation and assessment of our needs, quality components, cost effective and very neat installation.\n\nDespite weather delays, the team worked late into the night to ensure we got off grid asap, much appreciated 👍",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "April 2023",
  },
  {
    name: "Andrew Henderson",
    avatar: null,
    rating: 5,
    text: "When loadshedding increased towards the end of last year I decided to get an inverter and battery installed. I got quotes from a number of companies, getting further than a quote proved challenging with all except Sunlogic. They quickly came out to do a site inspection and responded rapidly to any questions I had. Once I'd decided to go with them they scheduled an installation date and kept me in the loop. Actually ended up being installed earlier than originally planned! The installation was smooth and the work is very neat and I haven't had an issues. Post installation they even came out to check the battery firmware. When I decide to take the next step and install solar panels I will definitely be going with Sunlogic.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "March 2023",
  },
  {
    name: "James Mason",
    avatar: null,
    rating: 5,
    text: "Very happy!",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "March 2023",
  },
  {
    name: "Esther Musikanth",
    avatar: null,
    rating: 5,
    text: "Last year December, I tried phoning 4 solar/inverter companies, 3 never came back to me, except for Craig from Sunlogic SA.  He came to assess the same day what I needed, sent a quote to me the same day and 2 weeks later his team installed our inverter.  Their after-sales service is also very good as we struggled to get our app to work but nothing was an issue for Stephan or Craig, they were obliging, honest and certainly out to please the Customer.  I have no hesitation in recommending them and know if they continue to offer the service I got, they will continue to do well!",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "February 2023",
  },
  {
    name: "Nathan SCOTT",
    avatar: null,
    rating: 5,
    text: "The Sunlogic team are consumate professionals who are clearly committed to service excellence. My experience with everyone at Sunlogic has been memorable and I have not one regret in having entrusted my solar installation to this great company.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "February 2023",
  },
  {
    name: "Denver Keswell",
    avatar: null,
    rating: 5,
    text: "“Fantastic Service” Stephan and Craig were professional from our first meeting until everything was running smoothly. Talked me through the entire installation and dealt with any teething issues immediately even if their team had to turn around in traffic after hours. Wasn’t just the installation that I was impressed with as their after sales service has been top notch. Highly recommend  them which I don’t often do. Thanks gents and look forward to adding to my plant in future.",
    url: "https://www.google.com/search?q=Sunlogic+SA+reviews",
    date: "February 2023",
  },
];
